pangeo-data/pangeo-docker-images

.github/workflows/watch-conda-forge.yml

closes #26 
We should repeat this for the metapackages as well.

add watch-conda-forge.yml action

---

.github/workflows/CondaLock.yml

Trying again with some simple fixes

Fixes for CondaLock chatops workflow

---

.github/workflows/WatchCondaForge.yml

fixed search and replace step. cc @jhamman

fix watchcondaforge action

---

README.md
base-notebook/conda-linux-64.lock
ml-notebook/conda-linux-64.lock
pangeo-notebook/conda-linux-64.lock

/condalock
Really just kicking a new build to get latest "panel" 0.9.5 build 1 on conda-forge.

force rebuild to get latest panel 

---

base-image/Dockerfile

closes https://github.com/pangeo-data/pangeo-docker-images/issues/66

allow for .binder/ as well as binder/

---

pangeo-notebook/environment.yml

To facilitate working with GDAL on AWS.

Adding awscli and jq

---

ml-notebook/conda-linux-64.lock
ml-notebook/environment.yml
ml-notebook/requirements.txt

cc @jhamman and @jsadler2. how has this environment been working? any new packages needed for ML workflows?

jupyterlab-nvdashboard from conda-forge instead of pip

---

base-image/dask_config.yml
tests/test_all.py

According to https://github.com/dask/dask-labextension/issues/135#issuecomment-651393102, this should work.

make dask gateway the default for labextension

---

README.md
base-image/start
base-notebook/start
ml-notebook/start
pangeo-notebook/start

I had the wrong environment variable earlier.

Fixed PANGEO_SCRATCH

---

pangeo-notebook/conda-linux-64.lock
pangeo-notebook/environment.yml

add cfgrib to pangeo-notebook

---

.github/workflows/CondaLock.yml
base-image/Dockerfile
base-notebook/conda-linux-64.lock
base-notebook/packages.txt
environment-condalock.yml
ml-notebook/conda-linux-64.lock
ml-notebook/packages.txt
pangeo-notebook/conda-linux-64.lock
pangeo-notebook/environment.yml
pangeo-notebook/packages.txt

bumps conda-lock and miniforge
should fix #139

bump versions, unpin

---

.github/workflows/ChatOpsDispatcher.yml
.github/workflows/Test.yml

solution to https://github.com/pangeo-data/pangeo-docker-images/pull/156#issuecomment-724333732

run tests when PR is opened

---

.github/workflows/CondaLock.yml
.github/workflows/Test.yml
base-image/Dockerfile

miniforge 4.9.0

---

pangeo-notebook/conda-linux-64.lock
pangeo-notebook/environment.yml
pangeo-notebook/packages.txt

https://github.com/davidbrochart/xarray_leaflet 
https://github.com/corteva/geocube

add geocube and xarray_leaflet

---

base-image/Dockerfile

Adding this to our base image will fix an obscure issue that prevents prefect agents from running in our envs.
see https://github.com/PrefectHQ/prefect/issues/3061

apt-get install tzdata

---

ml-notebook/conda-linux-64.lock
pangeo-notebook/conda-linux-64.lock
pangeo-notebook/environment.yml
pangeo-notebook/packages.txt

the ability to create gists from the command line is pretty great `gh gist create --public -d"s2-scene-classification-map" s2-scl-cloud-mask.ipynb`, among other nice things: https://github.com/cli/cli

add github cli

---

base-notebook/conda-linux-64.lock
base-notebook/packages.txt
ml-notebook/conda-linux-64.lock
ml-notebook/packages.txt
pangeo-notebook/conda-linux-64.lock
pangeo-notebook/environment.yml
pangeo-notebook/packages.txt

Now that https://github.com/intake/fsspec-reference-maker has published releases on pip/conda-forge, it might be nice to have it built into the Pangeo Cloud image.

Added fsspec-reference-maker to environment.yml

---

.github/workflows/Binder.yml
.github/workflows/BinderPR.yml
.github/workflows/Build.yml
.github/workflows/ChatOpsDispatcher.yml
.github/workflows/CondaLock.yml
.github/workflows/PR.yml
.github/workflows/Publish.yml
.github/workflows/Test.yml
environment-condalock.yml

Addresses #121 
Also bumps versions on github actions steps

bump github actions, add quay.io

---

.github/workflows/CondaLock.yml

Cache full conda environment rather than just downloaded packages

---

base-image/Dockerfile

Update base-image Dockerfile

---

.github/workflows/CondaLock.yml

Supersedes d72bd0fe2e4832258aba650eb344c9014e554229. Resolve timeout issue happening at #607 and other PRs.

Increase conda-lock timeout from 45 min to 2 hours
