.github/workflows/weekly-build.yml, .gitignore, weekly-build.log
This adds a cronjob workflow to trigger a new staging build once per week by adding the date to `week-build.log` 
```
2020.02.25
```
=> add weekly staging build github action

base-image/Dockerfile, base-image/condarc, base-image/dask_config.yml, base-notebook/environment.yml, base-worker/environment.yml, pangeo-notebook/environment.yml, pangeo-worker/environment.yml
now that metapackages are on conda-forge (https://github.com/pangeo-data/conda-metapackages/issues/1), we can use only that channel for conda config and environment.yml files
=> use only conda-forge channel

.github/workflows/ChatOps.yml, .github/workflows/CondaLock.yml, .github/workflows/WatchCondaForge.yml
This addresses some pieces of https://github.com/pangeo-data/pangeo-stacks-dev/issues/27. In particular it will enable generating lockfiles from PRs using "ChatOps" (https://github.com/peter-evans/slash-command-dispatch). 
So in theory someone edits environment.yml in there fork and creates a PR. Then in a PR comment writes:
/condalock
Then a bot will run conda-lock and add the lockfiles for each image into the PR. I'll probably follow up with some direct commits to test this out or additional PRs.
=> try chatops for condalock

.github/workflows/WatchCondaForge.yml
new metapackages on conda-forge will now trigger a PR - https://github.com/pangeo-data/pangeo-stacks-dev/pull/40 
this small change should trigger the separate condalock workflow, which solves for the conda environment, commits package lock files, then rebuilds images with those lock files and runs tests.
cc @jhamman
=> automatically run condalock workflow for watchcondaforge action

.github/workflows/WatchCondaForge.yml
Previous PR (https://github.com/pangeo-data/pangeo-stacks-dev/pull/40) didn't automatically retrigger building due to not using secrets.PERSONAL_TOKEN for the `/condalock` command in the PR message body. This adds the command as a separate comment on an existing PR.
=> move condalock command to separate PR comment

.github/workflows/Publish.yml
This allows tagging a production release retrospectively. Previously, the workflow would pull the 'master' tag and retag with '$CALVER' and 'latest'. If multiple PRs get merged in between pushing tags there was no way to tag docker images from previous commits. 
For example `git tag 2020.06.19 d4b3c1e ; git push upstream --tags` would pull `pangeo/base-image:master` instead of `pangeo/base-image:d4b3c1e`
=> modify publish github workflow for production releases

README.md, base-image/start, base-notebook/start, ml-notebook/start, pangeo-notebook/start
xref https://github.com/pangeo-data/pangeo-cloud-federation/issues/610,
https://github.com/pangeo-data/pangeo/pull/780. This adds a
PANGEO_SCRATCH environment variable. It relies on the existence of
1. PANGEO_SCRATCH_PROTOCOL
2. JUPYTERHUB_USERNAME
And combines those to form something like
`PANGEO_SCRATCH=gcs://pangeo-scratch/tomaugspurger`
We'll need to update the helm charts to set `PANGEO_SCRATCH_PROTOCOL` to be `s3` or `gcs`. This is a bit convoluted but I couldn't think of a simpler way.
=> Add a PANGEO_SCRATCH variable

base-notebook/conda-linux-64.lock, ml-notebook/conda-linux-64.lock, pangeo-notebook/conda-linux-64.lock, pangeo-notebook/environment.yml
See #101 . For some reason, we also need to force cartopy >= 0.18 to get mpi installed.
=> added esmpy and specified cartopy version

base-notebook/conda-linux-64.lock, base-notebook/packages.txt, ml-notebook/conda-linux-64.lock, ml-notebook/packages.txt, pangeo-notebook/conda-linux-64.lock, pangeo-notebook/environment.yml, pangeo-notebook/packages.txt
erddapy is a lightweight package to help interact with the [ERDDAP RESTful API](https://coastwatch.pfeg.noaa.gov/erddap/rest.html#requests), commonly used for environmental sensor data.
erddapy only depends on pytz and requests, both already in the environment.
=> add erddapy to notebook environment

.github/workflows/ChatOpsDispatcher.yml, .github/workflows/Test.yml
sometimes you want to manually trigger the Test workflow from a PR comment (https://github.com/pangeo-data/pangeo-docker-images/pull/156) 
This allows you to add `/test` as the first line of a comment to re-run CI
=> add /test slash command to re-run ci

.github/workflows/Test.yml
was missing the `-command` suffix for repository dispatch type: 
```
name: Test
on:
repository_dispatch:
types: [test-command]
```
=> fix for test slash command

.github/workflows/Test.yml
another follow up to https://github.com/pangeo-data/pangeo-docker-images/pull/157. not sure if this will work, it can get confusing to know against which commit and branch slash commands are running. might be better to break into completely separate .yml files...
=> fix test workflow checkout

base-image/Dockerfile
New LTS that's been out for a while. The most relavant
feature here is support for R 4.0, which traditionally
brings base R from the debian package. All prebuilt libraries
from https://packagemanager.rstudio.com/client/#/repos/1/packages
are built against focal for R 4.0 - so it becomes quite
difficult to use prebuilt R packages with 4.0 on bionic.
=> Bump base image to Ubuntu 20.04

base-image/Dockerfile, ml-notebook/jupyter_notebook_config.py, pangeo-notebook/jupyter_notebook_config.py
This PR solves the issue below. It does so in two steps.
1. Adds the feature base-image feature to detects a `jupyter_notebook_config.py` file and injects it to the otherwise empty folder `/etc/jupyter`.
2. It adds a `jupyter_notebook_config.py` file to the `pangeo-notebook` and `ml-notebook` folder that have `nb_conda_kernels` and configures it to avoid register a jupyter kernel twice.
The pangeo-notebook and ml-notebook install nb_conda_kernels, which will scan conda environments and register jupyter kernels based on installed packages in those kernels. But, if a kernel is already registered it will be registered again.
This can be avoided though, if we for example have a `/etc/jupyter/jupyter_notebook_config.py` available like this...
```python
import os …
```
=> Let base-image recognize jupyter_notebook_config.py, and configure nb_conda_kernels to not register a kernel again

base-notebook/conda-linux-64.lock, base-notebook/packages.txt, ml-notebook/conda-linux-64.lock, ml-notebook/packages.txt, pangeo-notebook/conda-linux-64.lock, pangeo-notebook/environment.yml, pangeo-notebook/packages.txt, pangeo-notebook/requirements.txt
following up #207 . Since we're using conda-lock files to build the image, we have a separate step for picking up pip installs from a requirements.txt instead of adding these under -pip: in the environment.yml
=> add stackstac in pip requirements.txt

README.md
The current link only works if you are logged in
=> Fix link to dockerhub org

.binder, .github/workflows/Binder.yml, .github/workflows/BinderPR.yml
I think this might remove the need for a separate pangeo-default-binder repository, by just soft linking the pangeo-notebook directory (`ln -s pangeo-notebook .binder`)
This way people would be able to use binder links like the following (optionally adding nbgitpuller links to specfic content)
* https://mybinder.org/v2/gh/pangeo-data/pangeo-docker-images/2021.09.22
* https://mybinder.org/v2/gh/pangeo-data/pangeo-docker-images/HEAD 
also adds binder links to PRs from https://github.com/jupyterhub/repo2docker-action, even running these images on mybinder.org can be helpful if not doing dask-gateway things...
related to #18
=> Enable binder links to pangeo-notebook image in this repository

README.md
This PR moves user-facing instructions to the top of the readme, and details on the building processes and instructions for pull requests in this repository to the bottom.
=> Move usage instructions higher up in readme, add more docs

base-image/Dockerfile
This is trying to fix an issue where executables in the conda environment are not in the environments PATH during the `requirements.txt` and `start` build steps. I ran into this when installing `git` via conda and installing a python package from source via the `requirements.txt` file.
=> export conda-env-path in requirements.txt and start build steps

README.md
This has come up in a few places, but it's worth documenting in the readme I think.
The idea is that sometimes people just want the conda environment (e.g. not actually using a dask cluster, or running on a hosted service like Colab or Sagemaker.
=> Add conda create command with remote lockfile

.github/workflows/CondaLock.yml, base-image/Dockerfile
A maintenance update of the miniforge version and mamba version. To avoid needing to make this kind of update too often, I've also added logic to specify the miniforge version by `major.minor` instead of doing it with `major.minor.patch-build`.
- The miniforge version was pinned to `4.10.3-7` and is via this PR pinned to be `4.11` which currently resolves to `4.11.0-0`.
- The mamba version was pinned to `0.17` and is now pinned to `0.20` which currently resolves to `0.20.0`.
Note that to specify the miniforge version by `major.minor` only, we needed logic to find the latest version matching that as the installation process is to download a specific URL including the exact version. This logic was implemented using a GitHub API and the CLI tool `jq` which was also added to parse out the …
=> Replace version pinned Miniforge with latest Mambaforge

get_version.sh
In https://github.com/2i2c-org/infrastructure/issues/1031  @choldgraf asked "What is the easiest way to answer the question "when did package X get updated in the Pangeo image, and which release is associated with it?"
This script is a quick way to answer that question. 
```
Getting package history for: distributed
=========
2022.02.04
distributed-2022.1.1
--
2022.01.31
distributed-2022.1.1
--
2021.12.02
distributed-2021.11.2
--
2021.11.09
distributed-2021.11.1
--
2021.11.07
distributed-2021.11.0
--
2021.11.04
distributed-2021.10.0
--
2021.10.19
distributed-2021.9.1
```
I also played around with a one-liner git command which is helpful for figuring out the *specific date and commit* that a package changed, but the you have to cross-reference our image date tags which are done manually and …
=> small bash script to get package versions in each tag

base-image/Dockerfile, base-notebook/Dockerfile, ml-notebook/Dockerfile, pangeo-notebook/Dockerfile
- Add a lot of inline documentation to the base-image, which is where
almost all the magic is.
- Install base-image packages in one go, rather than in two
lines - this is slightly faster.
- Hide stdout from apt-get install from base-image and from
apt-get update, but not for packages from apt.txt. Earlier
stderr was being hidden - but that is useful when the package
installation actually fails
- Use `--no-cache` instead of `--no-cache-dir` when installing
with pip, to be clearer on what we want.
=> Document the base-image & minor cleanup

base-notebook/conda-linux-64.lock, base-notebook/packages.txt, ml-notebook/conda-linux-64.lock, ml-notebook/packages.txt, pangeo-notebook/conda-linux-64.lock, pangeo-notebook/environment.yml, pangeo-notebook/packages.txt, pangeo-notebook/requirements.txt
This lets you *safely* push to GitHub from a properly configured GitHub.
See https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f
(draft blog post) for more information
=> Add gh-scoped-creds to base-notebook

ml-notebook/Dockerfile
These are required for `nvidia-smi` and generally anything that touches the GPU to
properly work on most containerized systems. We could set this at the hub level, but
this is cleaner and reduces workload for hub admins.
=> Set nvidia specific env vars in ml-notebook

README.md
Follow up of #315 to document how to run the `pytorch-notebook` docker image.
Output of `docker run -it --rm --gpus all pangeo/pytorch-notebook:master nvidia-smi` should show something like this:
```
Thu Apr 28 02:21:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0 …
```
=> Document how to run pytorch-notebook docker container

ml-notebook/apt.txt, pangeo-notebook/apt.txt, pytorch-notebook/apt.txt
`groff` is a declared dependency for the `awscli` as seen in
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.
Without `groff`, running `aws help` will lead to a failure.
Closes #216.
Please review that it makes sense to add groff to all these `apt.txt` files (`.binder/`, `pangeo-notebook/`, `ml-notebook/`, `pytorch-notebook/`). I'm both confused about finding a `.binder` folder and its relevance, as well as considering that ml/pytorch somehow depends on the pangeo-notebook.
=> Add groff, dependency for awscli

forge/Dockerfile, forge/start, tests/test_forge.py
- Fiddle with the `start` script, so it launches the beam boot binary correctly. Had to
fix how we were detecting the boot binary being called, as well as how we were calling
`exec` - args' first param needs to be the name of the command for commandline parsing
to work properl
- GCP DataFlow unfortunately expects the container to run as root - it mounts some directories
under `/var/opt` as root and expects the launched process to be able to read / write to it :( This
we should raise upstream and find some way to fix - but in the meantime, the forge image now
defaults to root. This shouldn't affect Jupyter use cases though, as we set the uid explicitly and
ignore what the image says most of the time.
=> Fixes pangeo forge image to be functional in Apache Beam environment 

.github/workflows/Binder.yml, .github/workflows/Build.yml, .github/workflows/Publish.yml, .github/workflows/Test.yml
* Switch to docker github actions such as (docker/build-push-action) that are more flexible for newer buildkit options (#357)
* Use only docker, not docker and podman for quay.io to speed up CI (fixes https://github.com/pangeo-data/pangeo-docker-images/issues/121#issuecomment-1279389501 
* Cancel concurrent Binder and Test workflows for PRs if multiple commits are made
=> Switch to buildx for github actions

base-image/Dockerfile
Panel and Xarray-Leaflet are heavy enough imports that without .pyc files, they sometimes together take as much as 15s to import?! This causes jupyterhub to fail startup in some cases.
The longer term fix is in panel and xarray-leaflet ( see https://github.com/holoviz/panel/issues/4271,
https://github.com/xarray-contrib/xarray_leaflet/issues/79).
In the meantime, leaving the .pyc files in place doesn't increase the image size by much, but makes startup definitely much faster!
Ref https://github.com/2i2c-org/infrastructure/issues/2047
=> Don't delete *.pyc files from the image

.readthedocs.yaml, README.md, docs/Makefile, docs/conf.py, docs/contributing.md, docs/howto/conda-env.md, docs/howto/custom-image.md, docs/howto/launch.md, docs/index.md, docs/make.bat, docs/requirements.txt, docs/topic/design.md, docs/topic/environment-variables.md
The README is getting a little crowded, and I think it will be very useful
to have a RTD site (similar to https://jupyter-docker-stacks.readthedocs.io/en/latest/)
that serves a broader audience. This set of images did start out as being used for
the pangeo JupyterHubs alone, but sees much broader use now.
2i2c also has some capacity to write the docs (https://github.com/2i2c-org/infrastructure/issues/2793).
I've already created a RTD setup for this!
=> Add a readthedocs setup

base-image/Dockerfile
We recently ran into the same problem encountered in https://github.com/PrefectHQ/prefect/issues/3061 / https://github.com/pangeo-data/pangeo-docker-images/pull/183 and https://github.com/pangeo-data/pangeo-docker-images/issues/125. This sets the TZ env variable so that prefect can be used with Pangeo docker images without any extra configuration needed.
=> Set TZ environment variable required for prefect

.github/workflows/Test.yml
Delete unused folders on the GitHub Actions runner to free up disk space for the docker build and test steps. Copied from 35f0c9a4ef31bcefe3ca0b7a8b6eb95553b2e02a.
Should help to prevent out of disk space errors on the pytorch-notebook test step, e.g. at https://github.com/pangeo-data/pangeo-docker-images/pull/475#issuecomment-1652832996
=> Free up disk space on Pull Request Test CI

.github/workflows/CondaLock.yml, environment-condalock.yml
Some updates cherry-picked from #514 to enable the CUDA upgrade from 11.8 to 12.0.
The 45min timeout might be a bit too generous, I can reduce it down to 30min or something after seeing what is actually required in #514 to lock the `pytorch-notebook` environment.
=> Bump conda-lock to 2.5, and increase locking timeout to 45min

.github/workflows/CondaLock.yml
Giving more time for conda-lock to solve the pytorch-notebook environment.
To help with https://github.com/pangeo-data/pangeo-docker-images/pull/545#issuecomment-2116033743 and https://github.com/pangeo-data/pangeo-docker-images/pull/514. Supersedes https://github.com/pangeo-data/pangeo-docker-images/pull/546
=> Increase conda-lock timeout to 3 hours

base-image/Dockerfile
Small change to test multiarch builds (following #399)
(I thought merging 399 would've pushed a multiarch image but it ran the existing 'Build' workflow on the master branch rather than the new one with QEMU https://github.com/pangeo-data/pangeo-docker-images/actions/runs/9706168740/job/26789540941)
=> Set dockerfile syntax version 

.github/workflows/Publish.yml
The `base-image`, `base-notebook` and `pangeo-notebook` Docker images only had linux/amd64 platform available on the latest and CalVer tags (see e.g. [`pangeo-notebook:2024.06.28`](https://hub.docker.com/layers/pangeo/pangeo-notebook/2024.06.28/images/sha256-48c57426f0d907fec00010f5e2aa54a190f72cdd84fb6413fd76733a323d295a?context=explore)), whereas the master tag has both `linux/amd64` and `linux/arm64`:
Need to use the `--platform` flag when doing `docker pull` or `docker push`, so that the linux/arm64 images will be made available for `latest` and Calver tags.
Patches #399
=> Publish CalVer tags for linux/arm64 platform builds

.github/workflows/Build.yml, .github/workflows/Publish.yml, .github/workflows/Test.yml
=> Fixes for multiarch docker image tagging

.github/workflows/ChatOpsDispatcher.yml, .github/workflows/CondaLock.yml
Was getting `Warning: Failed to set reaction on comment ID XXX` and `Adding reaction 'hooray' to comment id 'XXX' failed` due to missing write permissions to pull-requests. Noticed this at https://github.com/pangeo-data/pangeo-docker-images/pull/602#issuecomment-3330258265, where earlier comments had emoji reactions, but latter ones didn't.
Changes to set `permissions: pull-requests: write` where needed, and also changed from using `PANGEOBOT_TOKEN` to the default `GITHUB_TOKEN` in one instance.
References:
- https://github.com/CryoInTheCloud/hub-image/blame/cd4cd01e83c3d512d3d8947c6af56dd316a8c6c0/.github/workflows/slash-command-dispatch.yml#L14-L16
- https://github.com/peter-evans/slash-command-dispatch/issues/376
- https://github.com/peter-evans/slash-command-dispatch/issues/147#issueco …
=> Fix permissions for chatops actions to add reactions

.github/workflows/ChatOpsDispatcher.yml
Fixes `Error: Resource not accessible by integration` mentioned at https://github.com/pangeo-data/pangeo-docker-images/pull/625/files#r2377352047
References:
- https://github.com/peter-evans/slash-command-dispatch/issues/147#issuecomment-1489438442
- https://github.com/peter-evans/repository-dispatch/issues/196#issuecomment-1504067029
=> Set permissions to contents: write to exec repository_dispatch event
